name: Clear cache

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clear cache
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            const caches = await github.paginate(github.rest.actions.getActionsCacheList, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            })
            core.info(`Deleting ${caches.length} caches`)
            for (const cache of caches) {
              core.info(`Deleting cache ${cache.id}: ${cache.key}`)
              await github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
