name: build RustDeskTempTopMostWindow

on:
  workflow_call:
    inputs:
        upload-artifact:
          type: boolean
          default: true
        target:
            description: 'Target'
            type: string
            default: 'windows-2022'
        configuration:
            description: 'Configuration'
            type: string
            default: 'Release'
        platform:
            description: 'Platform'
            type: string
            default: 'x64'
        target_version:
            description: 'TargetVersion'
            type: string
            default: 'Windows10'

env:
  project_path: WindowInjection/WindowInjection.vcxproj

jobs:
  build-RustDeskTempTopMostWindow:
    runs-on: ${{ inputs.target }}
    timeout-minutes: 15
    strategy:
        fail-fast: false
    env:
      build_output_dir: RustDeskTempTopMostWindow/WindowInjection/${{ inputs.platform }}/${{ inputs.configuration }}
    steps:
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3

      - name: Download the source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          repository: rustdesk-org/RustDeskTempTopMostWindow
          ref: ecd8d6a139eee76845ea66423fb739af450fda90
          path: RustDeskTempTopMostWindow
          persist-credentials: false

      - name: Build the project
        run: |
          cd RustDeskTempTopMostWindow
          msbuild ${{ env.project_path }} -p:Configuration=${{ inputs.configuration }} -p:Platform=${{ inputs.platform }} /p:TargetVersion=${{ inputs.target_version }}

      - name: Archive build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ inputs.upload-artifact }}
        with:
            name: topmostwindow-artifacts-${{ inputs.platform }}
            path: |
              ./${{ env.build_output_dir }}/WindowInjection.dll
